time interval to query parameter
Acceede-HQ/Credit-ML pull request #2
Opened 2024-03-20 14:06 UTC by Platayo

What's New?
-implemented the start and end time interval on the mono query

2024-03-20 16:51 UTC, marxprop requested changes

2024-03-20 16:51 UTC, marxprop commented on MLModel.py
> +def get_date():
Change this function name to get_transaction_date_range instead.

2024-03-20 16:51 UTC, marxprop commented on MLModel.py
> +end = get_date()[1]
Ensure you call the function just once and inside the get transactions function instead (not outside)
Start and End are very vague variable names too. You might want to use clearer variable names.

`start_date, end_date = get_transaction_date_range()`

2024-03-20 16:51 UTC, marxprop commented on MLModel.py
> +    return start_date, end_date
You might want to update this function logic to be more simpler.
```
def get_transaction_date_range():
    current_date = datetime.now()
    end_date = current_date.strftime("%d-%m-%Y")
    start_date = (current_date - timedelta(days=365)).strftime("%d-%m-%Y")
    return start_date, end_date
```

2024-03-20 16:51 UTC, marxprop commented on MLModel.py
> +    return start_date, end_date
Please test this see if it does the same thing.

2024-03-20 17:58 UTC, Platayo commented
I affected the changes. The code you provided worked.

2024-03-20 18:25 UTC, marxprop requested changes

2024-03-20 18:25 UTC, marxprop commented on MLModel.py
> +start_date, end_date = get_transaction_date_range()
This should be inside in the `get_transactions` function instead so it is only used when calling the get_transactions function.

2024-03-20 18:28 UTC, marxprop commented
@Platayo, Other things to look at
- Once you've fixed a requested change, you can press the `Resolve conservation` button for each comment.
- At the right hand pane, under the Development section, please select the issue this PR is resolving and link it.

2024-03-21 15:53 UTC, marxprop approved these changes

2024-03-21 15:53 UTC, merged

2024-03-21 15:57 UTC, marxprop commented on MLModel.py
> +    url = f"https://api.withmono.com/accounts/{account_id}/transactions?paginate=false&start_date&end_date"
Ensure that start_date and end_date are in parentheses.
Please open another PR for that. Missed that before merging
@Platayo